apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: {{crdlowerpluralname}}.{{crdlowergroupname}}
spec:
  group: {{crdlowergroupname}}
  names:
    plural: {{crdlowerpluralname}}
    singular: {{crdlowername}}
    kind: {{crdlowername}}
    listKind: {{crdlowerpluralname}}
    shortNames:
      - {{crdlowershortname}}
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
# include here more properties for your custom CRD and 
# modify the {{crdName}}ResourceSpec.cs to represent this properties
            someproperty:
              type: string
          required:
            - someproperty
