name: Lucecu CI Build
on: push
jobs:
  build:
    env:
      VERSION_SUFFIX: -preview${{ github.run_id }}
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
        source-url: https://nuget.pkg.github.com/Xabaril/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: dotnet pack
      run: dotnet pack ./src/templates/k8soperator/Xabaril.Lucecu.K8SOperator.csproj --version-suffix $VERSION_SUFFIX --output ./artifacts
    - name: Push to GitHub package registry
      run: dotnet nuget push ./artifacts/*.nupkg