name: Lucecu CI Build
on: push
jobs:
  build:
    env:
      VERSION_SUFFIX: -preview${{ github.run_id }}
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
    - name: dotnet pack
      run: dotnet pack ./src/templates/k8soperator/Xabaril.Lucecu.K8SOperator.csproj --version-suffix $VERSION_SUFFIX --output ./artifacts
    - name: Publish nuget
      run: |
          for f in ./artifacts/*.nupkg
          do
            echo "Publishing $f"
            curl --silent --show-error --fail -vX PUT -u "Xabaril:${{ secrets.GITHUB_TOKEN }}" -F package=@$f https://nuget.pkg.github.com/Xabaril/
            if [ $? -eq 0 ]
            then
              echo "successfully pushed $f"
            else
              echo "failed to push $f" >&2
              exit 1
            fi
          done
      shell: bash